// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.contacts.domain;

import com.malsolo.contacts.domain.Contact;
import com.malsolo.contacts.domain.ContactDataOnDemand;
import com.malsolo.contacts.domain.ContactIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContactIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContactIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContactIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContactIntegrationTest: @Transactional;
    
    @Autowired
    ContactDataOnDemand ContactIntegrationTest.dod;
    
    @Test
    public void ContactIntegrationTest.testCountContacts() {
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", dod.getRandomContact());
        long count = Contact.countContacts();
        Assert.assertTrue("Counter for 'Contact' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContactIntegrationTest.testFindContact() {
        Contact obj = dod.getRandomContact();
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide an identifier", id);
        obj = Contact.findContact(id);
        Assert.assertNotNull("Find method for 'Contact' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Contact' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContactIntegrationTest.testFindAllContacts() {
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", dod.getRandomContact());
        long count = Contact.countContacts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Contact', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Contact> result = Contact.findAllContacts();
        Assert.assertNotNull("Find all method for 'Contact' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Contact' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContactIntegrationTest.testFindContactEntries() {
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", dod.getRandomContact());
        long count = Contact.countContacts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Contact> result = Contact.findContactEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Contact' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Contact' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContactIntegrationTest.testFlush() {
        Contact obj = dod.getRandomContact();
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide an identifier", id);
        obj = Contact.findContact(id);
        Assert.assertNotNull("Find method for 'Contact' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContact(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Contact' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactIntegrationTest.testMergeUpdate() {
        Contact obj = dod.getRandomContact();
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide an identifier", id);
        obj = Contact.findContact(id);
        boolean modified =  dod.modifyContact(obj);
        Integer currentVersion = obj.getVersion();
        Contact merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Contact' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", dod.getRandomContact());
        Contact obj = dod.getNewTransientContact(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Contact' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Contact' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContactIntegrationTest.testRemove() {
        Contact obj = dod.getRandomContact();
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide an identifier", id);
        obj = Contact.findContact(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Contact' with identifier '" + id + "'", Contact.findContact(id));
    }
    
}
