// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.contacts.domain;

import com.malsolo.contacts.domain.ContactIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ContactIntegrationTest_Roo_Configurable {
    
    declare @type: ContactIntegrationTest: @Configurable;
    
}
